version: '3.6'

services:
  config-server:
    build:
      context: config-server
      dockerfile: server.dockerfile
    ports:
      - "8080:8080"
    networks:
      - network1
 
networks:
  network1:
    driver: bridge