version: '3.6'

services:
  eureka-server:
    build:
      context: eureka-server
      dockerfile: eureka.dockerfile
    ports:
      - "9000:9000"
    networks:
      - network1
  book:
    build:
      context: book
      dockerfile: book.dockerfile
    ports:
      - "8090:8090"
    networks:
      - network1
    environment:
      - CONFIG_SERVER_URI=config-server
      - EUREKA_SERVER_URI=eureka-server
    depends_on:
      - eureka-server
 
networks:
  network1:
    driver: bridge