version: '3.6'

services:
  config-server:
    build:
      context: config-server
      dockerfile: config.dockerfile
    ports:
      - "8080:8080"
    networks:
      - network1

  eureka-server:
    build:
      context: eureka-server
      dockerfile: eureka.dockerfile
    ports:
      - "9000:9000"
    networks:
      - network1

  book:
    build:
      context: book
      dockerfile: book.dockerfile
    ports:
      - "8090:8090"
    networks:
      - network1
    depends_on:
      - config-server
      - eureka-server
    environment:
      - CONFIG_SERVER_URI=config-server
      - EUREKA_SERVER_URI=eureka-server


networks:
  network1:
    driver: bridge